[package]
name = "bma-benchmark"
version = "0.0.1"
edition = "2018"
license = "MIT"
authors = ["Sergei S. <div@altertech.com>"]
repository = "https://github.com/alttch/bma-benchmark"
description = "Rust benchmark tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
